name: memo_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  provider: ^6.0.5
  path: ^1.8.1
  shared_preferences: ^2.2.0
  flutter_locales: ^3.0.1
  path_provider: ^2.0.15
  persian_datetime_picker: ^2.6.0
  intl: ^0.18.0
  shamsi_date: ^1.0.1
  pdf: ^3.10.4
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/photos/
    - assets/locales/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
